- block:
  - command: dpkg --add-architecture i386
    args:
      creates: /var/lib/dpkg/arch
    when: ansible_architecture != 'i386'
    register: archrc

  - package:
      update_cache: true
    when: archrc is defined and archrc.changed

  - package:
      name:
        - "lib32stdc++6"
        - "libasound2-plugins:i386"
        - "libxt6:i386"
        - "libgtk2.0-0:i386"
        - "libnss3:i386"
        - "libcurl3-gnutls:i386"
        - "libidn11:i386"
        - "libpango1.0-0:i386"
        - "libpangox-1.0-0:i386"
        - "libpangoxft-1.0-0:i386"
        - "libxft2:i386"
      state: latest
  become: yes
  become_method: sudo

- command: unzip "{{ installer.path }}" -d "{{ tmp_folder }}"
  args:
    warn: false
  ignore_errors: yes

- copy:
    src: "{{ tmp_folder }}/data/noarch/"
    dest: "{{ app_folder }}"

- file:
    dest: "{{ app_folder }}/{{ executable }}"
    mode: a+x

# TODO: handle saves from ~/.macromedia/Flash_Player/#SharedObjects/X2Y42Q4T/#localWithNet/home/robert/yag/apps/machinarium/game/Machinarium
