- package:
    name: innoextract
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family | lower == "freebsd"

- stat:
    path: "/usr/bin/innoextract"
  register: app_installed

- block:
  - get_url:
      url: "https://constexpr.org/innoextract/files/innoextract-{{ innoextract_ver }}-linux.tar.xz"
      dest: "{{ tmp_folder }}"
      checksum: md5:33bdf359c62d4f88a51ae15048ea480e
  - unarchive:
      src: "{{ tmp_folder }}/innoextract-{{ innoextract_ver }}-linux.tar.xz"
      dest: "{{ tmp_folder }}"
  - copy:
      src: "{{ tmp_folder }}/innoextract-{{ innoextract_ver }}-linux/bin/amd64/innoextract"
      dest: "/usr/bin/"
      mode: a+x
    become: yes
    become_method: sudo
  vars:
    innoextract_ver: 1.9
  when: ansible_os_family | lower == "debian" and not app_installed.stat.exists
