- block:
    - assert:
        that:
          - installer is defined or image is defined
        fail_msg: please provide a source
    - include_role:
        name: scummvm
    - include_tasks: "install_image.yml"
      when: image is defined
  when: action == "install"

- include_tasks: "run.yml"
  when: action == "run"
