- innoextract:
    installer: "{{ installer.path }}"
    dest: "{{ tmp_folder }}"
    gog: true
    creates: "{{ tmp_folder }}/RData.lzma"

- copy:
    src: "{{ item }}"
    dest: "{{ app_folder }}"
  with_items:
    - "{{ tmp_folder }}/RData.Audio"
    - "{{ tmp_folder }}/{{ executable }}"
    - "{{ tmp_folder }}/RData.lzma"
    - "{{ tmp_folder }}/Galaxy.dll"

- wine:
    state: present
  register: wine_env

- set_fact:
    wine_data_folder: "{{ wine_env.prefix }}/drive_c/users/{{ ansible_user_id }}/Application Data/CasualBrothers/3Skulls/default"

- file:
    path: "{{ wine_data_folder }}"
    recurse: yes
    state: directory

- template:
    src: config.j2
    dest: "{{ wine_data_folder }}/config.txt"

- file:
    src: "{{ data_folder }}"
    dest: "{{ wine_data_folder }}/Savegames"
    force: yes
    state: link
