- block:
    - assert:
        that:
          - installer is defined or image is defined
        fail_msg: please provide a source
    - include_role:
        name: wine
    - include_tasks: "install_image.yml"
      when: image is defined
    - include_tasks: "install_{{ installer.subtype }}.yml"
      when: installer is defined
  when: action == "install"

- include_tasks: "run.yml"
  when: action == "run"
