- block:
  - include_role:
      name: scummvm
  - include_tasks: "install_{{ installer.type }}.yml"
    when: installer is defined
  - include_tasks: "install_patch.yml"
  when: action == "install"

- include_tasks: "{{ action }}.yml"
  when: action == "run"
