- block:
    - include_role:
        name: wine
    - include_tasks: "install_{{ installer.type }}.yml"
      when: installer is defined
  when: action == "install"

- include_tasks: "{{ action }}.yml"
  when: action == "run"
