- block:
    - assert:
        that:
          - installer is defined or image is defined
        fail_msg: please specify source
    - include_role:
        name: wine
    - include_tasks: "install_{{ installer.type }}.yml"
      when: installer is defined
    - include_tasks: "install_image.yml"
      when: image is defined
  when: action == "install"

- include_tasks: "{{ action }}.yml"
  when: action == "run"
