- image_extract:
    image: "{{ image.path }}"
    dest: "{{ app_folder }}"
    force: no

- copy:
    src: GOLDENGA.EXE
    dest: "{{ app_folder }}"

- wine:
    recipe: "{{ wine_recipe }}"
    exec: "{{ app_folder }}/QTIME32/QT32INST.EXE"
