- block:
  - command: dpkg --add-architecture i386
    args:
      creates: /var/lib/dpkg/arch
    when: ansible_architecture != 'i386'
    register: archrc

  - apt_key:
      url: https://dl.winehq.org/wine-builds/winehq.key
      state: present

  - apt_repository:
      repo: deb https://dl.winehq.org/wine-builds/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} main
      state: present

  - apt_repository:
      repo: ppa:cybermax-dexter/sdl2-backport
      state: present

  - package:
      name:
        - winehq-stable
        - wine-stable
        - wine-stable-i386
        - wine-stable-amd64
        - libgnutls30:i386
        - libldap-2.4-2:i386
        - libgpg-error0:i386
        - libxml2:i386
        - libasound2-plugins:i386
        - libsdl2-2.0-0:i386
        - libfreetype6:i386
        - libdbus-1-3:i386
        - libsqlite3-0:i386
        - libfaudio0:i386
        - winetricks
      state: latest
      update_cache: true
      install_recommends: true

  become: yes
  become_method: sudo
