- block:
    - include_role:
        name: scummvm
    - include_tasks: "install_image.yml"
      when: image is defined
    - include_tasks: "install_{{ installer.subtype }}.yml"
      when: installer is defined
  when: action == "install"

- include_tasks: "run.yml"
  when: action == "run"
